
device: cpu
ros_config:
  a_range: 0.5
  v_range: 0.5
grid_config:
  x_semidim: 1.0
  y_semidim: 1.0
  num_grid_cells: 400
  mini_grid_radius: 1
  n_targets: 1
  n_targets_per_class: 1
experiment_config:
  desc: null
  value:
    sampling_device: cpu
    train_device: cpu
    buffer_device: cpu
    share_policy_params: true
    prefer_continuous_actions: true
    collect_with_grad: false
    parallel_collection: false
    gamma: 0.99
    lr: 5.0e-05
    adam_eps: 1.0e-06
    clip_grad_norm: true
    clip_grad_val: 5
    soft_target_update: true
    polyak_tau: 0.005
    hard_target_update_frequency: 5
    exploration_eps_init: 0.8
    exploration_eps_end: 0.01
    exploration_anneal_frames: null
    max_n_iters: null
    max_n_frames: 20000000
    on_policy_collected_frames_per_batch: 50000
    on_policy_n_envs_per_worker: 250
    on_policy_n_minibatch_iters: 45
    on_policy_minibatch_size: 4000
    off_policy_collected_frames_per_batch: 6000
    off_policy_n_envs_per_worker: 10
    off_policy_n_optimizer_steps: 1000
    off_policy_train_batch_size: 128
    off_policy_memory_size: 1000000
    off_policy_init_random_frames: 0
    off_policy_use_prioritized_replay_buffer: false
    off_policy_prb_alpha: 0.6
    off_policy_prb_beta: 0.4
    evaluation: true
    render: true
    evaluation_interval: 200000
    evaluation_episodes: 1
    evaluation_deterministic_actions: true
    loggers:
    - csv
    project_name: benchmarl
    create_json: true
    save_folder: "/Users/nicolaspfitzer/ProrokLab/CustomScenarios/outputs"
    restore_file: null
    restore_map_location: null
    checkpoint_interval: 150000
    checkpoint_at_end: false
    keep_checkpoints_num: 3
algorithm_config:
  desc: null
  value:
    share_param_critic: true
    clip_epsilon: 0.2
    entropy_coef: 0.0001
    critic_coef: 1.0
    loss_critic_type: l2
    lmbda: 0.9
    scale_mapping: biased_softplus_1.0
    use_tanh_normal: true
    minibatch_advantage: false
model_config:
  desc: null
  value:
    num_cells:
    - 256
    - 256
    - 256
    layer_class: torch.nn.modules.linear.Linear
    activation_class: torch.nn.modules.activation.ReLU
    activation_kwargs: null
    norm_class: null
    norm_kwargs: null
task_config:
  desc: null
  value:
    max_steps: 200
    n_agents: 1
    n_targets_per_class: 1
    n_target_classes: 1
    x_semidim: 1.0
    y_semidim: 1.0
    mini_grid_radius: 1
    comms_radius: 0.3
    use_gnn: false
    n_obstacles: 0
    global_heading_objective: false
    num_grid_cells: 400
    data_json_path: data/language_data_complete_multi_target_color_medium.json
    decoder_model_path: decoders/llm0_decoder_model_grid_single_target_color.pth
    llm_activate: true
    use_decoder: false
    use_grid_data: true
    use_class_data: false
    use_max_targets_data: false
    observe_pos_history: true
    observe_targets: true
    history_length: 4
continuous_actions:
  desc: null
  value: true
on_policy:
  desc: null
  value: true
algorithm_name:
  desc: null
  value: mappo
model_name:
  desc: null
  value: mlp
task_name:
  desc: null
  value: navigation
environment_name:
  desc: null
  value: vmas
seed:
  desc: null
  value: 0
